### ISSUE TITLE
Java 16 not supported

### ISSUE THREAD

**Issue by ptunde** [PocketByte/LocoLaser#14]
Hi,

I was using this tool for a while in a native iOS app (version 1.2.4) and today it stopped getting my localisation files. I'm getting this in my Terminal window.

```
Artifact ru.pocketbyte.locolaser:core:2.0.0 already downloaded
Artifact ru.pocketbyte.locolaser:resource-mobile:2.0.0 already downloaded
Artifact ru.pocketbyte.locolaser:resource-googlesheet:2.0.0 already downloaded
ERROR: java.lang.RuntimeException: Failed to read list of execution jars
	at ru.pocketbyte.locolaser.ConfigParserFactory.getJarUrls(ConfigParserFactory.kt:67)
	at ru.pocketbyte.locolaser.ConfigParserFactory.getFromClassLoader(ConfigParserFactory.kt:26)
	at ru.pocketbyte.locolaser.ConfigParserFactory.get(ConfigParserFactory.kt:19)
	at ru.pocketbyte.locolaser.Main.main(Main.kt:20)
Caused by: java.lang.NoSuchFieldException: ucp
	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
	at ru.pocketbyte.locolaser.ConfigParserFactory.getJarUrls(ConfigParserFactory.kt:58)
	... 3 more
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

The same error persisted after migrating to version 2.0.0. Also I'm getting the same error when run the localize.command from the iOS sample app.

Any help would be much appreciated.

**Comment by KamiSempai** [comment]
I found that LocoLaser doesn't working on Java 16 and above. For now try to use JDK 15 or lower.
I will fix it soon.

**Comment by ptunde** [comment]
Thank you for the update. I will downgrade to Java 15.

**Comment by KamiSempai** [comment]
Fixed in version 2.1.0. Please note, that new version uploaded only in Maven Central. JCenter no more available.

**Comment by ptunde** [comment]
Sorry, but something is still wrong, after I run the .localize.command from Terminal it redirects me to the browser, where is an Authorisation error (401: invalid_client), however I'm logged into my account.

Screenshoots attached below
![Screenshot 2021-05-03 at 15 01 26](https://user-images.githubusercontent.com/13233102/116879940-9f36d080-ac21-11eb-84bf-827650069930.png)
![Screenshot 2021-05-03 at 15 06 28](https://user-images.githubusercontent.com/13233102/116879949-a231c100-ac21-11eb-9c3e-0a76ff5adf4d.png)

**Comment by KamiSempai** [comment]
@ptunde this is a known issue #8 .See comments for correct solution.

**Comment by ptunde** [comment]
Oh right, thanks for the help.
